# Generated by Django 3.2.12 on 2022-02-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setter', '0002_auto_20220212_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Some Title', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
