# Generated by Django 3.2.12 on 2022-02-13 13:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setter', '0004_alter_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
